{% set version = "6.4.0" %}
{% set variant = "openblas" %}

package:
  name: ncl
  version: {{ version }}

source:
  url: https://github.com/NCAR/ncl/archive/{{ version }}.tar.gz
  sha256: 0962ae1a1d716b182b3b27069b4afe66bf436c64c312ddfcf5f34d4ec60153c8

build:
  number: 7
  skip: True  # [win]
  features:
    - blas_{{ variant }}  # [not win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*  # [linux]
    - curl >=7.54.1,<8
    - freetype 2.8.*  # [linux]
    - g2clib 1.6.*
    - gsl 2.2.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    # FIXME: We cannot use hdfeos5 b/c it won't compiled with hdf5 1.10.1
    # - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.2.*
    - libiconv 1.15
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - pixman 0.34.*  # [linux]
    - proj4 4.9.3
    - udunits2
    - zlib 1.2.11
    - gcc
    - pkg-config
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*  # [linux]
    - curl >=7.54.1,<8
    - freetype 2.8.*  # [linux]
    - g2clib 1.6.*
    - gsl 2.2.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    # FIXME: We cannot use hdfeos5 b/c it won't compiled with hdf5 1.10.1
    # - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.2.*
    - libiconv 1.15
    - libnetcdf 4.4.*
    - libpng >=1.6.32,<1.6.35
    - pixman 0.34.*  # [linux]
    - proj4 4.9.3
    - udunits2
    - zlib 1.2.11
    - esmf
    - libgcc
    - xorg-imake  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-makedepend  # [linux]

test:
  source_files:
    - install/make-tarfile/check_files
  commands:
    - test "$(ncl -V)" = "{{ version }}"
    - NCARG_ROOT=${PREFIX} install/make-tarfile/check_files | grep -qv '^<'
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://ncl.ucar.edu/
  license: 'NCL Source Code'
  license_file: COPYING
  summary: 'NCAR Command Language'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
