{% set version = "6.6.2" %}

package:
  name: ncl
  version: {{ version }}

source:
  - url: https://github.com/NCAR/ncl/archive/{{ version }}.tar.gz
    sha256: cad4ee47fbb744269146e64298f9efa206bc03e7b86671e9729d8986bb4bc30e
    patches:
      - 0000-grib2.patch
      - 0001-extern-vars.patch
      - 0002-port-to-proj-6-api.patch
      - 0003-boz-fix.patch
      - jasper2.patch
      - osx-arm64.patch
      - int-conversion.patch  # [osx]
      - jasper-jpc.patch
  - url: https://netlib.sandia.gov/voronoi/triangle.zip
    sha256: 1766327add038495fa3499e9b7cc642179229750f7201b94f8e1b7bee76f8480
    folder: triangle_tmp

build:
  number: 46
  skip: True  # [win]
  features:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - xorg-imake  # [linux]
    - xorg-makedepend
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - make  # [unix]
  host:
    - libblas
    - libcblas
    - bzip2
    - cairo  # [linux]
    - curl
    - freetype  # [linux]
    - gsl
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libiconv
    - libjpeg-turbo
    - libnetcdf
    - libpng
    - pixman  # [linux]
    - proj
    - udunits2
    - zlib
    - flex
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-libxt   # [linux]
  run:
    - bzip2
    - cairo  # [linux]
    - curl
    - freetype  # [linux]
    - gsl
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal
    - libiconv
    - libjpeg-turbo
    - libnetcdf
    - libpng
    - pixman  # [linux]
    - proj
    - udunits2
    - zlib
    - esmf
    - xorg-imake  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-makedepend  # [linux]

test:
  source_files:
    - install/make-tarfile/check_files
  requires:
    - coreutils
    - git
    - imagemagick
  commands:
    - test "$(ncl -V)" = "{{ version }}"
    - NCARG_ROOT=${PREFIX} install/make-tarfile/check_files | grep -qv '^<'
    - git clone https://github.com/NCAR/ncl_ci_test && cd ncl_ci_test && export NCARG_ROOT=${PREFIX} && bash -x run_tests.bash

about:
  home: http://ncl.ucar.edu/
  license: Apache-2.0 and LicenseRef-Proprietary-Triangle
  license_file:
    - LICENSE
    - LICENSE_triangle.txt
  summary: NCAR Command Language

extra:
  recipe-maintainers:
    - erogluorhan
    - akrherz
    - zklaus
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
    - xylar
