{% set version = "6.6.0" %}
{% set variant = "openblas" %}

package:
  name: ncl
  version: {{ version }}

source:
  url: https://github.com/NCAR/ncl/archive/{{ version }}.tar.gz
  sha256: d8202340a878e78c88454d136ea796d7dc7677d0df31739c0d15598c95ee35e7
  patches:
    - grib2.patch

build:
  number: 0
  skip: True  # [win]
  features:
    - blas_{{ variant }}  # [not win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - xorg-imake  # [linux]
    - xorg-makedepend  # [linux]
  host:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2
    - cairo  # [linux]
    - curl
    - freetype  # [linux]
    - gsl
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg
    - libgdal
    - libiconv
    - libnetcdf
    - libpng
    - pixman  # [linux]
    - proj4
    - udunits2
    - zlib
    - flex
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - openmp  # [osx]
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2
    - cairo  # [linux]
    - curl
    - freetype  # [linux]
    - gsl
    - hdf4
    - hdf5
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg
    - libgdal
    - libiconv
    - libnetcdf
    - libpng
    - pixman  # [linux]
    - proj4
    - udunits2
    - zlib
    - esmf
    - xorg-imake  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxmu  # [linux]
    - xorg-libxrender  # [linux]
    - xorg-makedepend  # [linux]
    - openmp  # [osx]

test:
  source_files:
    - install/make-tarfile/check_files
  commands:
    - test "$(ncl -V)" = "{{ version }}"
    - NCARG_ROOT=${PREFIX} install/make-tarfile/check_files | grep -qv '^<'
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://ncl.ucar.edu/
  license: 'Apache 2.0'
  license_file: LICENSE
  summary: 'NCAR Command Language'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
