{% set version = "6.4.0" %}
{% set variant = "openblas" %}

package:
  name: ncl
  version: {{ version }}

source:
  fn: ncl-{{ version }}.tar.gz
  url: https://github.com/NCAR/ncl/archive/{{ version }}.tar.gz
  sha256: 0962ae1a1d716b182b3b27069b4afe66bf436c64c312ddfcf5f34d4ec60153c8

build:
  number: 5
  skip: True  # [win]
  features:
    - blas_{{ variant }}  # [not win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*
    - curl
    - flex
    - freetype 2.7
    - g2clib 1.6.*
    - gsl
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.1.*
    - libiconv
    - libnetcdf 4.4.*
    - libpng >=1.6.28,<1.7
    - pixman 0.34.*
    - pkg-config
    - proj4 4.9.3
    - udunits2
    - xorg-imake
    - xorg-libx11
    - xorg-libxaw
    - xorg-libxmu
    - xorg-libxrender
    - xorg-makedepend
    - zlib 1.2.8
  run:
    - libgcc
    - blas 1.1 {{ variant }}  # [not win]
    - bzip2 1.0.*
    - cairo 1.14.*
    - curl
    - esmf
    - freetype 2.7
    - g2clib 1.6.*
    - gsl
    - hdf4
    - hdf5 1.8.18|1.8.18.*
    - hdfeos2
    - hdfeos5
    - jasper
    - jpeg 9*
    - libgdal 2.1.*
    - libiconv
    - libnetcdf 4.4.*
    - libpng >=1.6.28,<1.7
    - pixman 0.34.*
    - proj4 4.9.3
    - udunits2
    - xorg-imake
    - xorg-libx11
    - xorg-libxaw
    - xorg-libxmu
    - xorg-libxrender
    - xorg-makedepend
    - zlib 1.2.8

test:
  source_files:
    - install/make-tarfile/check_files
  commands:
    - test "$(ncl -V)" = "{{ version }}"
    - NCARG_ROOT=${PREFIX} install/make-tarfile/check_files | grep -qv '^<'
    - conda inspect linkages -p $PREFIX ncl  # [not win]
    - conda inspect objects -p $PREFIX ncl  # [osx]

about:
  home: http://ncl.ucar.edu/
  license: 'NCL Source Code'
  license_file: COPYING
  summary: 'NCAR Command Language'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
    - ocefpaf
